name = "ac-photoshare"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ALBUMS"
id = "f89da5bbc2094c9cb389eee063df15b5"

[vars]
SITE_URL = "https://e2cd94a6.ac-photoshare.pages.dev"
